apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: wbh-caf-cpf-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: wbh-caf-cpf-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /webhook/caf/cpf_validation
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /webhook/caf/cpf_validation
