apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: caf-cpf-val-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: caf-cpf-val-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /webhook/caf/cpf-validation
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /webhook/caf/cpf-validation
