include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-J623

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: wbh-caf-cpf-fn-35f75d73-0375-475a-b6d9-75a52c71fbf0
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-J623
  environment:
    name: wbh-caf-cpf-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-09T19:20:32Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: wbh-caf-cpf-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: wbh-caf-cpf-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: wbh-caf-cpf-fn-35f75d73-0375-475a-b6d9-75a52c71fbf0
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
